# pubspec.yaml
name: microsleep
description: "A Flutter app for eye detection - open/close detection"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  provider: ^6.1.1
  image_picker: ^1.0.4
  google_mlkit_face_detection: ^0.10.0
  tflite_flutter: ^0.11.0
  image: ^3.0.1
  path_provider: ^2.1.1
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/panda.png"
